TABLE_SIZE=1000  #just reading

# PARAMETERS
TMAX = 32
TMAX_RESTORE_VALUE = TMAX
MINIMUM_TMAX = 10

# FILE NAME
HOSTS = 7
FILE_NAME = 'univ1_pt'
'''
medium
univ1_pt1  -- 1..5
small_univ11
'''

# PROACTIVE EVICTION
LOW_THRESHOLD = 0.55
HIGH_THRESHOLD = 0.85

# SET IDLE TIMEOUT

COEF_95 = 0.75  #TMAX coef
B_VALUE = 1
IDLE_LOWER_THRESHOLD = 0.4
IDLE_HIGH_THRESHOLD = 0.8