/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
/**
 * @file part_b_client.c
 * @author Elif Kızılkaya
 
 * @brief Code for part B for the project EXPLAIN
 *
 *
 * EXPLANATION
 * How to compile and run:
    make
    ./part_a.out blackbox part_a_output.txt
 */


#include "part_b.h"
#include<sys/types.h>
#include<sys/stat.h>
#include <fcntl.h> 
#include <stdio.h>
#include <unistd.h>
#define CREATE_FLAGS (O_WRONLY | O_CREAT | O_APPEND)
#define CREATE_MODE (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)

void
part_b_prog_1(char *host, char* path1, char* path2, int input1, int input2)
{
	CLIENT *clnt;
	char * *result_1;
	parameters  part_b_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PART_B_PROG, PART_B_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	part_b_1_arg.path = path1; //path of the executable blackbox
	//printf("path ::%s\n", part_b_1_arg.path);
	part_b_1_arg.number1 = input1;
	part_b_1_arg.number2 = input2;
	
	result_1 = part_b_1(&part_b_1_arg, clnt);

	//printf("%s %d %d sdjsndj\n", part_b_1_arg.path, part_b_1_arg.number1, part_b_1_arg.number2);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{

		/*
			Write the output to the file
			path2 is the path of the output file
		*/
		//printf("Result = %s", *result_1);
		int fd;

        fd = open(path2, CREATE_FLAGS, CREATE_MODE);
        if (fd == -1) {
            perror("Failed to open output gile");
            return;
        }
        if (dup2(fd, STDOUT_FILENO) == -1) {
            perror("Failed to redirect standard output");
            return;
        }
        if (close(fd) == -1) {
            perror("Failed to close the file");
            return;
        }

        char text[10000];
        sprintf(text, "%lu", atol(*result_1));

        if (strlen(*result_1) == (strlen(text) + 1)) {
             printf("SUCCESS:\n%s", *result_1);
        }
        else {

             printf("FAIL:\n%s", *result_1);
        }



	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[3];
	int input1;
	int input2;
	scanf("%d %d", &input1, &input2);
	//printf("%s %s %s %d %d\n", argv[3], argv[2], argv[1], input1, input2);
	part_b_prog_1 (host, argv[1], argv[2], input1, input2);
exit (0);
}
